﻿services:
  kali-crakit:
    build: # Build de l'image
      context: . # Répertoire courant Dockerfile
    image: kali-crakit:latest
    container_name: kali-crakit
    restart: unless-stopped # Conteneur redémarre en cas de crash 
    ports:
      - "2222:22"
    volumes:
      # Persister le partage des wordlists, userlists et hashfiles de l'user en cas de supression ou rebuild
      - ./CraKit/Assets/wordlists:/root/wordlists   
      - ./CraKit/Assets/userlists:/root/userlists
      - ./CraKit/Assets/hashfiles:/root/hashfiles   
      - ./Crakit/Assets/combolists:/root/combolists
    tty: true



    
